/***************************************************************************
//
// ACCEPT.CPP
//
// TAPI Service provider for TSP++ version 3.00
// lineAccept handler
//
// Copyright (C) 1999 JulMar Technology, Inc.
// All rights reserved
//
// Generated by the TSPWizard (C) JulMar Technology, Inc.
// 
/***************************************************************************/

/*----------------------------------------------------------------------------
	INCLUDE FILES
-----------------------------------------------------------------------------*/
#include "stdafx.h"
#include "ConfTest.h"

/*****************************************************************************
** Procedure:  CConfTestLine::OnAccept
**
** Arguments: 'pReq' - Request object representing this Accept event 
**            'lpBuff' - The passed opaque block of data
**
** Returns:    void
**
** Description:  This function manages the lineAccept processing
**               for this service provider.
**
*****************************************************************************/
bool CConfTestLine::OnAccept(RTAccept* pRequest, LPCVOID lpBuff)
{
	CTSPICallAppearance* pCall = pRequest->GetCallInfo();
	if (pRequest->EnterState(STATE_INITIAL, STATE_WAITING))
	{
		pCall->SetCallState(LINECALLSTATE_ACCEPTED);
		CompleteRequest(pRequest, 0);
	}
	return false;

}// CConfTestLine::OnAccept

