/***************************************************************************
//
// ANSWER.CPP
//
// TAPI Service provider for TSP++ version 3.00
// lineAnswer handler
//
// Copyright (C) 1999 JulMar Technology, Inc.
// All rights reserved
//
// Generated by the TSPWizard (C) JulMar Technology, Inc.
// 
/***************************************************************************/

/*----------------------------------------------------------------------------
	INCLUDE FILES
-----------------------------------------------------------------------------*/
#include "stdafx.h"
#include "ConfTest.h"

/*****************************************************************************
** Procedure:  CConfTestLine::OnAnswer
**
** Arguments: 'pReq' - Request object representing this ANSWER event 
**            'lpBuff' - The event block pointer
**
** Returns:    void
**
** Description:  This function manages the TSPI_lineAnswer processing
**               for this service provider.
**
*****************************************************************************/
bool CConfTestLine::OnAnswer(RTAnswer* pRequest, LPCVOID lpBuff)
{
	CTSPICallAppearance* pCall = pRequest->GetCallInfo();
	if (pRequest->EnterState(STATE_INITIAL, STATE_WAITING))
	{
		pCall->SetCallState(LINECALLSTATE_CONNECTED);
		CompleteRequest(pRequest, 0);
	}
	return false;

}// CConfTestLine::OnAnswer

