/***************************************************************************
//
// DROPCALL.CPP
//
// TAPI Service provider for TSP++ version 3.00
// lineDrop management
//
// Copyright (C) 1999 JulMar Technology, Inc.
// All rights reserved
//
// Generated by the TSPWizard (C) JulMar Technology, Inc.
// 
/***************************************************************************/

/*----------------------------------------------------------------------------
	INCLUDE FILES
-----------------------------------------------------------------------------*/
#include "stdafx.h"
#include "ConfTest.h"

/*****************************************************************************
** Procedure:  CConfTestLine::OnDropCall
**
** Arguments: 'pReq' - Request object representing this DROPCALL event 
**            'lpBuff' - The event block pointer
**
** Returns:    void
**
** Description:  This function manages the TSPI_lineDrop processing
**               for this service provider.
**
*****************************************************************************/
bool CConfTestLine::OnDropCall(RTDropCall* pRequest, LPCVOID lpBuff)
{
	CTSPICallAppearance* pCall = pRequest->GetCallInfo();
	if (pRequest->EnterState(STATE_INITIAL, STATE_WAITING))
	{
		if (pCall->GetCallType() == CTSPICallAppearance::Conference)
		{
			CTSPIConferenceCall* pConf = dynamic_cast<CTSPIConferenceCall*>(pCall);
			while(pConf->GetConferenceCount() > 0)
			{
				CTSPICallAppearance* pCall = pConf->GetConferenceCall(0);
				pCall->SetCallState(LINECALLSTATE_IDLE);
			}
			pConf->SetCallState(LINECALLSTATE_IDLE);
		}
		else
		{
			pCall->SetCallState(LINECALLSTATE_IDLE);
		}
		CompleteRequest(pRequest, 0);
	}
	return false;

}// CConfTestLine::OnDropCall

