/*---------------------------------------------------------------------------*/
// Bitmask conversion structures
/*---------------------------------------------------------------------------*/

static DWtoString _AddressCaps[] = {
	{ LINEADDRCAPFLAGS_FWDNUMRINGS,		_T("FWDNUMRINGS") },           
	{ LINEADDRCAPFLAGS_PICKUPGROUPID,	_T("PICKUPGROUPID") },         
	{ LINEADDRCAPFLAGS_SECURE,			_T("SECURE") },                
	{ LINEADDRCAPFLAGS_BLOCKIDDEFAULT,	_T("BLOCKIDDEFAULT") },        
	{ LINEADDRCAPFLAGS_BLOCKIDOVERRIDE,	_T("BLOCKIDOVERRIDE") },       
	{ LINEADDRCAPFLAGS_DIALED,			_T("DIALED") },                
	{ LINEADDRCAPFLAGS_ORIGOFFHOOK,		_T("ORIGOFFHOOK") },           
	{ LINEADDRCAPFLAGS_DESTOFFHOOK,		_T("DESTOFFHOOK") },           
	{ LINEADDRCAPFLAGS_FWDCONSULT,		_T("FWDCONSULT") },            
	{ LINEADDRCAPFLAGS_SETUPCONFNULL,	_T("SETUPCONFNULL") },         
	{ LINEADDRCAPFLAGS_AUTORECONNECT,	_T("AUTORECONNECT") },         
	{ LINEADDRCAPFLAGS_COMPLETIONID,	_T("COMPLETIONID") },          
	{ LINEADDRCAPFLAGS_TRANSFERHELD,	_T("TRANSFERHELD") },          
	{ LINEADDRCAPFLAGS_TRANSFERMAKE,	_T("TRANSFERMAKE") },          
	{ LINEADDRCAPFLAGS_CONFERENCEHELD,	_T("CONFERENCEHELD") },        
	{ LINEADDRCAPFLAGS_CONFERENCEMAKE,	_T("CONFERENCEMAKE") },        
	{ LINEADDRCAPFLAGS_PARTIALDIAL,		_T("PARTIALDIAL") },           
	{ LINEADDRCAPFLAGS_FWDSTATUSVALID,	_T("FWDSTATUSVALID") },        
	{ LINEADDRCAPFLAGS_FWDINTEXTADDR,	_T("FWDINTEXTADDR") },         
	{ LINEADDRCAPFLAGS_FWDBUSYNAADDR,	_T("FWDBUSYNAADDR") },         
	{ LINEADDRCAPFLAGS_ACCEPTTOALERT,	_T("ACCEPTTOALERT") },         
	{ LINEADDRCAPFLAGS_CONFDROP,		_T("CONFDROP") },              
	{ LINEADDRCAPFLAGS_PICKUPCALLWAIT,	_T("PICKUPCALLWAIT") },        
	{ LINEADDRCAPFLAGS_PREDICTIVEDIALER,_T("PREDICTIVEDIALER") },      
	{ LINEADDRCAPFLAGS_QUEUE,			_T("QUEUE") },                 
	{ LINEADDRCAPFLAGS_ROUTEPOINT,		_T("ROUTEPOINT") },            
	{ LINEADDRCAPFLAGS_HOLDMAKESNEW,	_T("HOLDMAKESNEW") },          
	{ LINEADDRCAPFLAGS_NOINTERNALCALLS,	_T("NOINTERNALCALLS") },       
	{ LINEADDRCAPFLAGS_NOEXTERNALCALLS,	_T("NOEXTERNALCALLS") },       
	{ LINEADDRCAPFLAGS_SETCALLINGID,	_T("SETCALLINGID") },          
	{ 0, NULL }
};

static DWtoString _AddressModes[] = {
	{ LINEADDRESSMODE_ADDRESSID,	_T("ADDRESSID") },              
	{ LINEADDRESSMODE_DIALABLEADDR, _T("DIALABLEADDR") },
	{ 0, NULL }
};

static DWtoString _AddressSharing[] = {
	{ LINEADDRESSSHARING_PRIVATE,			_T("PRIVATE") },             
	{ LINEADDRESSSHARING_BRIDGEDEXCL,		_T("BRIDGEDEXCL") },         
	{ LINEADDRESSSHARING_BRIDGEDNEW,		_T("BRIDGEDNEW") },          
	{ LINEADDRESSSHARING_BRIDGEDSHARED,		_T("BRIDGEDSHARED") },       
	{ LINEADDRESSSHARING_MONITORED,			_T("MONITORED") },           
	{ 0, NULL }
};

static DWtoString _AddressStates[] = {
	{ LINEADDRESSSTATE_OTHER,		_T("OTHER") },
	{ LINEADDRESSSTATE_DEVSPECIFIC, _T("DEVSPECIFIC") },
	{ LINEADDRESSSTATE_INUSEZERO,	_T("INUSEZERO") },
	{ LINEADDRESSSTATE_INUSEONE,    _T("INUSEONE") },
	{ LINEADDRESSSTATE_INUSEMANY,   _T("INUSEMANY") },
	{ LINEADDRESSSTATE_NUMCALLS,    _T("NUMCALLS") },
	{ LINEADDRESSSTATE_FORWARD,     _T("FORWARD") },
	{ LINEADDRESSSTATE_TERMINALS,   _T("TERMINALS") },
	{ LINEADDRESSSTATE_CAPSCHANGE,  _T("CAPSCHANGE") },
	{ 0, NULL }
};

static DWtoString _AddressFeatures[] = {
	{ LINEADDRFEATURE_FORWARD,			_T("FORWARD") },                
	{ LINEADDRFEATURE_MAKECALL,			_T("MAKECALL") },               
	{ LINEADDRFEATURE_PICKUP,			_T("PICKUP") },                 
	{ LINEADDRFEATURE_SETMEDIACONTROL,	_T("SETMEDIACONTROL") },        
	{ LINEADDRFEATURE_SETTERMINAL,		_T("SETTERMINAL") },            
	{ LINEADDRFEATURE_SETUPCONF,		_T("SETUPCONF") },              
	{ LINEADDRFEATURE_UNCOMPLETECALL,	_T("UNCOMPLETECALL") },         
	{ LINEADDRFEATURE_UNPARK,			_T("UNPARK") },                 
	{ LINEADDRFEATURE_PICKUPHELD,		_T("PICKUPHELD") },             
	{ LINEADDRFEATURE_PICKUPGROUP,		_T("PICKUPGROUP") },            
	{ LINEADDRFEATURE_PICKUPDIRECT,		_T("PICKUPDIRECT") },           
	{ LINEADDRFEATURE_PICKUPWAITING,	_T("PICKUPWAITING") },          
	{ LINEADDRFEATURE_FORWARDFWD,		_T("FORWARDFWD") },             
	{ LINEADDRFEATURE_FORWARDDND,		_T("FORWARDDND") },             
	{ 0, NULL }
};

static DWtoString _AgentFeatures[] = {
	{ LINEAGENTFEATURE_SETAGENTGROUP,		_T("SETAGENTGROUP") },         
	{ LINEAGENTFEATURE_SETAGENTSTATE,		_T("SETAGENTSTATE") },         
	{ LINEAGENTFEATURE_SETAGENTACTIVITY,	_T("SETAGENTACTIVITY") },      
	{ LINEAGENTFEATURE_AGENTSPECIFIC,		_T("AGENTSPECIFIC") },         
	{ LINEAGENTFEATURE_GETAGENTACTIVITYLIST,_T("GETAGENTACTIVITYLIST") },  
	{ LINEAGENTFEATURE_GETAGENTGROUP,		_T("GETAGENTGROUP") },         
	{ 0, NULL }
};

static DWtoString _AgentStates[] = {
	{ LINEAGENTSTATE_LOGGEDOFF,			_T("LOGGEDOFF") },               
	{ LINEAGENTSTATE_NOTREADY,			_T("NOTREADY") },                
	{ LINEAGENTSTATE_READY,				_T("READY") },                   
	{ LINEAGENTSTATE_BUSYACD,			_T("BUSYACD") },                 
	{ LINEAGENTSTATE_BUSYINCOMING,		_T("BUSYINCOMING") },            
	{ LINEAGENTSTATE_BUSYOUTBOUND,		_T("BUSYOUTBOUND") },            
	{ LINEAGENTSTATE_BUSYOTHER,			_T("BUSYOTHER") },               
	{ LINEAGENTSTATE_WORKINGAFTERCALL,	_T("WORKINGAFTERCALL") },        
	{ LINEAGENTSTATE_UNKNOWN,			_T("UNKNOWN") },                 
	{ LINEAGENTSTATE_UNAVAIL,			_T("UNAVAIL") },                 
	{ 0, NULL }
};

static DWtoString _AgentStatusFlags[] = {
	{ LINEAGENTSTATUS_GROUP,			_T("GROUP") },
	{ LINEAGENTSTATUS_STATE,			_T("STATE") },
	{ LINEAGENTSTATUS_NEXTSTATE,		_T("NEXTSTATE") },
	{ LINEAGENTSTATUS_ACTIVITY,			_T("ACTIVITY") },
	{ LINEAGENTSTATUS_ACTIVITYLIST,     _T("ACTIVITYLIST") },
	{ LINEAGENTSTATUS_GROUPLIST,        _T("GROUPLIST") },
	{ LINEAGENTSTATUS_CAPSCHANGE,       _T("CAPSCHANGE") },
	{ LINEAGENTSTATUS_VALIDSTATES,      _T("VALIDSTATES") },
	{ LINEAGENTSTATUS_VALIDNEXTSTATES,  _T("VALIDNEXTSTATES") },
	{ 0, NULL }
};


static DWtoString _AnswerMode[] = {
	{ LINEANSWERMODE_NONE,			_T("NONE") },                    
	{ LINEANSWERMODE_DROP,			_T("DROP") },                    
	{ LINEANSWERMODE_HOLD,			_T("HOLD") },                    
	{ 0, NULL },
};

static DWtoString _BearerModes[] = {
	{ LINEBEARERMODE_VOICE,				_T("VOICE") },                   
	{ LINEBEARERMODE_SPEECH,			_T("SPEECH") },                  
	{ LINEBEARERMODE_MULTIUSE,			_T("MULTIUSE") },                
	{ LINEBEARERMODE_DATA,				_T("DATA") },                    
	{ LINEBEARERMODE_ALTSPEECHDATA,		_T("ALTSPEECHDATA") },           
	{ LINEBEARERMODE_NONCALLSIGNALING,	_T("NONCALLSIGNALING") },        
	{ LINEBEARERMODE_PASSTHROUGH,		_T("PASSTHROUGH") },             
	{ LINEBEARERMODE_RESTRICTEDDATA,	_T("RESTRICTEDDATA") },          
	{ 0, NULL }
};

static DWtoString _BusyModes[] = {
	{ LINEBUSYMODE_STATION,		_T("STATION") },
	{ LINEBUSYMODE_TRUNK,		_T("TRUNK") },
	{ LINEBUSYMODE_UNKNOWN,		_T("UNKNOWN") },
	{ LINEBUSYMODE_UNAVAIL,		_T("UNAVAIL") },
	{ 0, NULL }
};

static DWtoString _CallPrivilege[] = {
	{ LINECALLPRIVILEGE_NONE,	 _T("NONE") },
	{ LINECALLPRIVILEGE_MONITOR, _T("MONITOR") },
	{ LINECALLPRIVILEGE_OWNER,	 _T("OWNER") },
	{ 0, NULL }
};

static DWtoString _CompletionConditions[] = {
	{ LINECALLCOMPLCOND_BUSY,		_T("BUSY") },                 
	{ LINECALLCOMPLCOND_NOANSWER,	_T("NOANSWER") },             
	{ 0, NULL }
};

static DWtoString _CompletionModes[] = {
	{ LINECALLCOMPLMODE_CAMPON,		_T("CAMPON") },               
	{ LINECALLCOMPLMODE_CALLBACK,	_T("CALLBACK") },             
	{ LINECALLCOMPLMODE_INTRUDE,	_T("INTRUDE") },              
	{ LINECALLCOMPLMODE_MESSAGE,	_T("MESSAGE") },              
	{ 0, NULL }
};

static DWtoString _CallFeatures[] = {
	{ LINECALLFEATURE_ACCEPT,			_T("ACCEPT") },                 
	{ LINECALLFEATURE_ADDTOCONF,		_T("ADDTOCONF") },              
	{ LINECALLFEATURE_ANSWER,			_T("ANSWER") },                 
	{ LINECALLFEATURE_BLINDTRANSFER,	_T("BLINDTRANSFER") },          
	{ LINECALLFEATURE_COMPLETECALL,		_T("COMPLETECALL") },           
	{ LINECALLFEATURE_COMPLETETRANSF,	_T("COMPLETETRANSF") },         
	{ LINECALLFEATURE_DIAL,				_T("DIAL") },                   
	{ LINECALLFEATURE_DROP,				_T("DROP") },                   
	{ LINECALLFEATURE_GATHERDIGITS,		_T("GATHERDIGITS") },           
	{ LINECALLFEATURE_GENERATEDIGITS,	_T("GENERATEDIGITS") },         
	{ LINECALLFEATURE_GENERATETONE,		_T("GENERATETONE") },           
	{ LINECALLFEATURE_HOLD,				_T("HOLD") },                   
	{ LINECALLFEATURE_MONITORDIGITS,	_T("MONITORDIGITS") },          
	{ LINECALLFEATURE_MONITORMEDIA,		_T("MONITORMEDIA") },           
	{ LINECALLFEATURE_MONITORTONES,		_T("MONITORTONES") },           
	{ LINECALLFEATURE_PARK,				_T("PARK") },                   
	{ LINECALLFEATURE_PREPAREADDCONF,	_T("PREPAREADDCONF") },         
	{ LINECALLFEATURE_REDIRECT,			_T("REDIRECT") },               
	{ LINECALLFEATURE_REMOVEFROMCONF,	_T("REMOVEFROMCONF") },         
	{ LINECALLFEATURE_SECURECALL,		_T("SECURECALL") },             
	{ LINECALLFEATURE_SENDUSERUSER,		_T("SENDUSERUSER") },           
	{ LINECALLFEATURE_SETCALLPARAMS,	_T("SETCALLPARAMS") },          
	{ LINECALLFEATURE_SETMEDIACONTROL,	_T("SETMEDIACONTROL") },        
	{ LINECALLFEATURE_SETTERMINAL,		_T("SETTERMINAL") },            
	{ LINECALLFEATURE_SETUPCONF,		_T("SETUPCONF") },              
	{ LINECALLFEATURE_SETUPTRANSFER,	_T("SETUPTRANSFER") },          
	{ LINECALLFEATURE_SWAPHOLD,			_T("SWAPHOLD") },               
	{ LINECALLFEATURE_UNHOLD,			_T("UNHOLD") },                 
	{ LINECALLFEATURE_RELEASEUSERUSERINFO,	_T("RELEASEUSERUSERINFO") },    
	{ LINECALLFEATURE_SETTREATMENT,		_T("SETTREATMENT") },           
	{ LINECALLFEATURE_SETQOS,			_T("SETQOS") },                 
	{ LINECALLFEATURE_SETCALLDATA,		_T("SETCALLDATA") },            
	{ 0, NULL }
};

static DWtoString _CallFeatures2[] = {
	{ LINECALLFEATURE2_NOHOLDCONFERENCE,	_T("NOHOLDCONFERENCE") },      
	{ LINECALLFEATURE2_ONESTEPTRANSFER,		_T("ONESTEPTRANSFER") },       
	{ LINECALLFEATURE2_COMPLCAMPON,			_T("COMPLCAMPON") },           
	{ LINECALLFEATURE2_COMPLCALLBACK,		_T("COMPLCALLBACK") },         
	{ LINECALLFEATURE2_COMPLINTRUDE,		_T("COMPLINTRUDE") },          
	{ LINECALLFEATURE2_COMPLMESSAGE,		_T("COMPLMESSAGE") },          
	{ LINECALLFEATURE2_TRANSFERNORM,		_T("TRANSFERNORM") },          
	{ LINECALLFEATURE2_TRANSFERCONF,		_T("TRANSFERCONF") },          
	{ LINECALLFEATURE2_PARKDIRECT,			_T("PARKDIRECT") },            
	{ LINECALLFEATURE2_PARKNONDIRECT,		_T("PARKNONDIRECT") },         
	{ 0, NULL }
};

static DWtoString _CallHubTrackModes[] = {
	{ LINECALLHUBTRACKING_NONE,				_T("NONE") },
	{ LINECALLHUBTRACKING_PROVIDERLEVEL,	_T("PROVIDER_LEVEL") },
	{ LINECALLHUBTRACKING_ALLCALLS,			_T("ALLCALLS") },
	{ 0, NULL }
};

static DWtoString _CIStates[] = {
	{ LINECALLINFOSTATE_OTHER,			_T("OTHER") },
	{ LINECALLINFOSTATE_DEVSPECIFIC,	_T("DEVSPECIFIC") },
	{ LINECALLINFOSTATE_BEARERMODE,		_T("BEARERMODE") },
	{ LINECALLINFOSTATE_RATE,			_T("RATE") },
	{ LINECALLINFOSTATE_MEDIAMODE,		_T("MEDIAMODE") },
	{ LINECALLINFOSTATE_APPSPECIFIC,	_T("APPSPECIFIC") },
	{ LINECALLINFOSTATE_CALLID,			_T("CALLID") },
	{ LINECALLINFOSTATE_RELATEDCALLID,	_T("RELATEDCALLID") },
	{ LINECALLINFOSTATE_ORIGIN,			_T("ORIGIN") },
	{ LINECALLINFOSTATE_REASON,			_T("REASON") },
	{ LINECALLINFOSTATE_COMPLETIONID,	_T("COMPLETIONID") },
	{ LINECALLINFOSTATE_NUMOWNERINCR,	_T("NUMOWNERINCR") },
	{ LINECALLINFOSTATE_NUMOWNERDECR,	_T("NUMOWNERDECR") },
	{ LINECALLINFOSTATE_NUMMONITORS,	_T("NUMMONITORS") },
	{ LINECALLINFOSTATE_TRUNK,			_T("TRUNK") },
	{ LINECALLINFOSTATE_CALLERID,		_T("CALLERID") },
	{ LINECALLINFOSTATE_CALLEDID,		_T("CALLEDID") },
	{ LINECALLINFOSTATE_CONNECTEDID,	_T("CONNECTEDID") },
	{ LINECALLINFOSTATE_REDIRECTIONID,	_T("REDIRECTIONID") },
	{ LINECALLINFOSTATE_REDIRECTINGID,	_T("REDIRECTINGID") },
	{ LINECALLINFOSTATE_DISPLAY,		_T("DISPLAY") },
	{ LINECALLINFOSTATE_USERUSERINFO,	_T("USERUSERINFO") },
	{ LINECALLINFOSTATE_HIGHLEVELCOMP,	_T("HIGHLEVELCOMP") },
	{ LINECALLINFOSTATE_LOWLEVELCOMP,	_T("LOWLEVELCOMP") },
	{ LINECALLINFOSTATE_CHARGINGINFO,	_T("CHARGINGINFO") },
	{ LINECALLINFOSTATE_TERMINAL,		_T("TERMINAL") },
	{ LINECALLINFOSTATE_DIALPARAMS,		_T("DIALPARAMS") },
	{ LINECALLINFOSTATE_MONITORMODES,	_T("MONITORMODES") },
	{ LINECALLINFOSTATE_TREATMENT,		_T("TREATMENT") },
	{ LINECALLINFOSTATE_QOS,			_T("QOS") },
	{ LINECALLINFOSTATE_CALLDATA,		_T("CALLDATA") },
	{ 0, NULL }
};

static DWtoString _CallOrigins[] = {
	{ LINECALLORIGIN_OUTBOUND,			_T("OUTBOUND") },                
	{ LINECALLORIGIN_INTERNAL,			_T("INTERNAL") },                
	{ LINECALLORIGIN_EXTERNAL,			_T("EXTERNAL") },                
	{ LINECALLORIGIN_UNKNOWN,			_T("UNKNOWN") },                 
	{ LINECALLORIGIN_UNAVAIL,			_T("UNAVAIL") },                 
	{ LINECALLORIGIN_CONFERENCE,		_T("CONFERENCE") },              
	{ LINECALLORIGIN_INBOUND,			_T("INBOUND") },                 
	{ 0, NULL }
};

static DWtoString _CallParamFlags[] = {
	{ LINECALLPARAMFLAGS_SECURE,			_T("SECURE") },              
	{ LINECALLPARAMFLAGS_IDLE,				_T("IDLE") },                
	{ LINECALLPARAMFLAGS_BLOCKID,			_T("BLOCKID") },             
	{ LINECALLPARAMFLAGS_ORIGOFFHOOK,		_T("ORIGOFFHOOK") },         
	{ LINECALLPARAMFLAGS_DESTOFFHOOK,		_T("DESTOFFHOOK") },         
	{ LINECALLPARAMFLAGS_NOHOLDCONFERENCE,	_T("NOHOLDCONFERENCE") },    
	{ LINECALLPARAMFLAGS_PREDICTIVEDIAL,	_T("PREDICTIVEDIAL") },      
	{ LINECALLPARAMFLAGS_ONESTEPTRANSFER,	_T("ONESTEPTRANSFER") },     
	{ 0, NULL }
};

static DWtoString _CIDFLags[] = {
	{ LINECALLPARTYID_BLOCKED,		_T("BLOCKED") },
	{ LINECALLPARTYID_OUTOFAREA,	_T("OUTOFAREA") },
	{ LINECALLPARTYID_NAME,			_T("NAME") },
	{ LINECALLPARTYID_ADDRESS,		_T("ADDRESS") },
	{ LINECALLPARTYID_PARTIAL,		_T("PARTIAL") },
	{ LINECALLPARTYID_UNKNOWN,		_T("UNKNOWN") },
	{ LINECALLPARTYID_UNAVAIL,		_T("UNAVAIL") },
	{ 0, NULL }
};

static DWtoString _CallReasons[] = {
	{ LINECALLREASON_DIRECT,			_T("DIRECT") },                  
	{ LINECALLREASON_FWDBUSY,			_T("FWDBUSY") },                 
	{ LINECALLREASON_FWDNOANSWER,		_T("FWDNOANSWER") },             
	{ LINECALLREASON_FWDUNCOND,			_T("FWDUNCOND") },               
	{ LINECALLREASON_PICKUP,			_T("PICKUP") },                  
	{ LINECALLREASON_UNPARK,			_T("UNPARK") },                  
	{ LINECALLREASON_REDIRECT,			_T("REDIRECT") },                
	{ LINECALLREASON_CALLCOMPLETION,	_T("CALLCOMPLETION") },          
	{ LINECALLREASON_TRANSFER,			_T("TRANSFER") },                
	{ LINECALLREASON_REMINDER,			_T("REMINDER") },                
	{ LINECALLREASON_UNKNOWN,			_T("UNKNOWN") },                 
	{ LINECALLREASON_UNAVAIL,			_T("UNAVAIL") },                 
	{ LINECALLREASON_INTRUDE,			_T("INTRUDE") },                 
	{ LINECALLREASON_PARKED,			_T("PARKED") },                  
	{ LINECALLREASON_CAMPEDON,			_T("CAMPEDON") },                
	{ LINECALLREASON_ROUTEREQUEST,		_T("ROUTEREQUEST") },            
	{ 0, NULL }
};

static DWtoString _CallStates[] = {
	{ LINECALLSTATE_IDLE,				_T("IDLE") },
	{ LINECALLSTATE_OFFERING,			_T("OFFERING") },
	{ LINECALLSTATE_ACCEPTED,			_T("ACCEPTED") },
	{ LINECALLSTATE_DIALTONE,			_T("DIALTONE") },
	{ LINECALLSTATE_DIALING,			_T("DIALING") },
	{ LINECALLSTATE_RINGBACK,			_T("RINGBACK") },
	{ LINECALLSTATE_BUSY,				_T("BUSY") },
	{ LINECALLSTATE_SPECIALINFO,		_T("SPECIALINFO") },
	{ LINECALLSTATE_CONNECTED,			_T("CONNECTED") },
	{ LINECALLSTATE_PROCEEDING,			_T("PROCEEDING") },
	{ LINECALLSTATE_ONHOLD,				_T("ONHOLD") },
	{ LINECALLSTATE_CONFERENCED,		_T("CONFERENCED") },
	{ LINECALLSTATE_ONHOLDPENDCONF,		_T("ONHOLDPENDCONF") },
	{ LINECALLSTATE_ONHOLDPENDTRANSFER,	_T("ONHOLDPENDTRANSFER") },
	{ LINECALLSTATE_DISCONNECTED,		_T("DISCONNECTED") },
	{ LINECALLSTATE_UNKNOWN,			_T("UNKNOWN") },
	{ 0, NULL }
};

static DWtoString _CallTreatments[] = {
	{ LINECALLTREATMENT_SILENCE,		_T("SILENCE") },              
	{ LINECALLTREATMENT_RINGBACK,		_T("RINGBACK") },             
	{ LINECALLTREATMENT_BUSY,			_T("BUSY") },                 
	{ LINECALLTREATMENT_MUSIC,			_T("MUSIC") },                
	{ 0, NULL }
};

static DWtoString _ConnectedModes[] = {
	{ LINECONNECTEDMODE_ACTIVE,			_T("ACTIVE") },               
	{ LINECONNECTEDMODE_INACTIVE,		_T("INACTIVE") },             
	{ LINECONNECTEDMODE_ACTIVEHELD,		_T("ACTIVEHELD") },           
	{ LINECONNECTEDMODE_INACTIVEHELD,	_T("INACTIVEHELD") },         
	{ LINECONNECTEDMODE_CONFIRMED,		_T("CONFIRMED") },            
	{ 0, NULL }
};

static DWtoString _DevCapFlags[] = {
	{ LINEDEVCAPFLAGS_CROSSADDRCONF,	_T("CROSSADDRCONF") },          
	{ LINEDEVCAPFLAGS_HIGHLEVCOMP,		_T("HIGHLEVCOMP") },            
	{ LINEDEVCAPFLAGS_LOWLEVCOMP,		_T("LOWLEVCOMP") },             
	{ LINEDEVCAPFLAGS_MEDIACONTROL,		_T("MEDIACONTROL") },           
	{ LINEDEVCAPFLAGS_MULTIPLEADDR,		_T("MULTIPLEADDR") },           
	{ LINEDEVCAPFLAGS_CLOSEDROP,		_T("CLOSEDROP") },              
	{ LINEDEVCAPFLAGS_DIALBILLING,		_T("DIALBILLING") },            
	{ LINEDEVCAPFLAGS_DIALQUIET,		_T("DIALQUIET") },              
	{ LINEDEVCAPFLAGS_DIALDIALTONE,		_T("DIALDIALTONE") },           
	{ LINEDEVCAPFLAGS_MSP,				_T("MSP") },
	{ LINEDEVCAPFLAGS_CALLHUB,		    _T("CALLHUB") },
	{ LINEDEVCAPFLAGS_CALLHUBTRACKING,  _T("CALLHUBTRACKING") },
	{ LINEDEVCAPFLAGS_PRIVATEOBJECTS,   _T("PRIVATEOBJECTS") },
	{ 0, NULL }
};

static DWtoString _DevStates[] = {
	{ LINEDEVSTATE_OTHER,			_T("OTHER") },                     
	{ LINEDEVSTATE_RINGING,			_T("RINGING") },                   
	{ LINEDEVSTATE_CONNECTED,		_T("CONNECTED") },                 
	{ LINEDEVSTATE_DISCONNECTED,	_T("DISCONNECTED") },              
	{ LINEDEVSTATE_MSGWAITON,		_T("MSGWAITON") },                 
	{ LINEDEVSTATE_MSGWAITOFF,		_T("MSGWAITOFF") },                
	{ LINEDEVSTATE_INSERVICE,		_T("INSERVICE") },                 
	{ LINEDEVSTATE_OUTOFSERVICE,	_T("OUTOFSERVICE") },              
	{ LINEDEVSTATE_MAINTENANCE,		_T("MAINTENANCE") },               
	{ LINEDEVSTATE_OPEN,			_T("OPEN") },                      
	{ LINEDEVSTATE_CLOSE,			_T("CLOSE") },                     
	{ LINEDEVSTATE_NUMCALLS,		_T("NUMCALLS") },                  
	{ LINEDEVSTATE_NUMCOMPLETIONS,	_T("NUMCOMPLETIONS") },            
	{ LINEDEVSTATE_TERMINALS,		_T("TERMINALS") },                 
	{ LINEDEVSTATE_ROAMMODE,		_T("ROAMMODE") },                  
	{ LINEDEVSTATE_BATTERY,			_T("BATTERY") },                   
	{ LINEDEVSTATE_SIGNAL,			_T("SIGNAL") },                    
	{ LINEDEVSTATE_DEVSPECIFIC,		_T("DEVSPECIFIC") },               
	{ LINEDEVSTATE_REINIT,			_T("REINIT") },                    
	{ LINEDEVSTATE_LOCK,			_T("LOCK") },                      
	{ LINEDEVSTATE_CAPSCHANGE,		_T("CAPSCHANGE") },                
	{ LINEDEVSTATE_CONFIGCHANGE,	_T("CONFIGCHANGE") },              
	{ LINEDEVSTATE_TRANSLATECHANGE,	_T("TRANSLATECHANGE") },           
	{ LINEDEVSTATE_COMPLCANCEL,		_T("COMPLCANCEL") },               
	{ LINEDEVSTATE_REMOVED,			_T("REMOVED") },                   
	{ 0, NULL }
};

static DWtoString _DevStatusFlags[] = {
	{ LINEDEVSTATUSFLAGS_CONNECTED,		_T("CONNECTED") },           
	{ LINEDEVSTATUSFLAGS_MSGWAIT,		_T("MSGWAIT") },             
	{ LINEDEVSTATUSFLAGS_INSERVICE,		_T("INSERVICE") },           
	{ LINEDEVSTATUSFLAGS_LOCKED,		_T("LOCKED") },              
	{ 0, NULL }
};

static DWtoString _DialToneModes[] = {
	{ LINEDIALTONEMODE_NORMAL,		_T("NORMAL") },
	{ LINEDIALTONEMODE_SPECIAL,		_T("SPECIAL") },
	{ LINEDIALTONEMODE_INTERNAL,	_T("INTERNAL") },
	{ LINEDIALTONEMODE_EXTERNAL,	_T("EXTERNAL") },
	{ LINEDIALTONEMODE_UNKNOWN,		_T("UNKNOWN") },
	{ LINEDIALTONEMODE_UNAVAIL,		_T("UNAVAIL") },
	{ 0, NULL }
};

static DWtoString _DigitModes[] = {
	{ LINEDIGITMODE_PULSE,	_T("PULSE") },
	{ LINEDIGITMODE_DTMF,	_T("DTMF") },
	{ LINEDIGITMODE_DTMFEND,_T("DTMFEND") },                  
	{ 0, NULL }
};

static DWtoString _DisconnectModes[] = {
	{ LINEDISCONNECTMODE_NORMAL,		_T("NORMAL") },
	{ LINEDISCONNECTMODE_UNKNOWN,		_T("UNKNOWN") },
	{ LINEDISCONNECTMODE_REJECT,		_T("REJECT") },
	{ LINEDISCONNECTMODE_PICKUP,		_T("PICKUP") },
	{ LINEDISCONNECTMODE_FORWARDED,		_T("FORWARDED") },
	{ LINEDISCONNECTMODE_BUSY,			_T("BUSY") },
	{ LINEDISCONNECTMODE_NOANSWER,		_T("NOANSWER") },
	{ LINEDISCONNECTMODE_BADADDRESS,	_T("BADADDRESS") },
	{ LINEDISCONNECTMODE_UNREACHABLE,	_T("UNREACHABLE") },
	{ LINEDISCONNECTMODE_CONGESTION,	_T("CONGESTION") },
	{ LINEDISCONNECTMODE_INCOMPATIBLE,	_T("INCOMPATIBLE") },
	{ LINEDISCONNECTMODE_UNAVAIL,		_T("UNAVAIL") },
	{ LINEDISCONNECTMODE_NODIALTONE,	_T("NODIALTONE") },
	{ LINEDISCONNECTMODE_NUMBERCHANGED,	_T("NUMBERCHANGED") },
	{ LINEDISCONNECTMODE_OUTOFORDER,	_T("OUTOFORDER") },
	{ LINEDISCONNECTMODE_TEMPFAILURE,	_T("TEMPFAILURE") },
	{ LINEDISCONNECTMODE_QOSUNAVAIL,	_T("QOSUNAVAIL") },
	{ LINEDISCONNECTMODE_BLOCKED,		_T("BLOCKED") },
	{ LINEDISCONNECTMODE_DONOTDISTURB,	_T("DONOTDISTURB") },
	{ LINEDISCONNECTMODE_CANCELLED,		_T("CANCELLED") },
	{ 0, NULL }
};

static DWtoString _ErrorCodes[] = {
	{ LINEERR_ALLOCATED,				_T("LINEERR_ALLOCATED") },                      
	{ LINEERR_BADDEVICEID,				_T("LINEERR_BADDEVICEID") },                    
	{ LINEERR_BEARERMODEUNAVAIL,		_T("LINEERR_BEARERMODEUNAVAIL") },              
	{ LINEERR_CALLUNAVAIL,				_T("LINEERR_CALLUNAVAIL") },                    
	{ LINEERR_COMPLETIONOVERRUN,		_T("LINEERR_COMPLETIONOVERRUN") },              
	{ LINEERR_CONFERENCEFULL,			_T("LINEERR_CONFERENCEFULL") },                 
	{ LINEERR_DIALBILLING,				_T("LINEERR_DIALBILLING") },                    
	{ LINEERR_DIALDIALTONE,				_T("LINEERR_DIALDIALTONE") },                   
	{ LINEERR_DIALPROMPT,				_T("LINEERR_DIALPROMPT") },                     
	{ LINEERR_DIALQUIET,				_T("LINEERR_DIALQUIET") },                      
	{ LINEERR_INCOMPATIBLEAPIVERSION,	_T("LINEERR_INCOMPATIBLEAPIVERSION") },         
	{ LINEERR_INCOMPATIBLEEXTVERSION,	_T("LINEERR_INCOMPATIBLEEXTVERSION") },         
	{ LINEERR_INIFILECORRUPT,			_T("LINEERR_INIFILECORRUPT") },                 
	{ LINEERR_INUSE,					_T("LINEERR_INUSE") },                          
	{ LINEERR_INVALADDRESS,				_T("LINEERR_INVALADDRESS") },                   
	{ LINEERR_INVALADDRESSID,			_T("LINEERR_INVALADDRESSID") },                 
	{ LINEERR_INVALADDRESSMODE,			_T("LINEERR_INVALADDRESSMODE") },               
	{ LINEERR_INVALADDRESSSTATE,		_T("LINEERR_INVALADDRESSSTATE") },              
	{ LINEERR_INVALAPPHANDLE,			_T("LINEERR_INVALAPPHANDLE") },                 
	{ LINEERR_INVALAPPNAME,				_T("LINEERR_INVALAPPNAME") },                   
	{ LINEERR_INVALBEARERMODE,			_T("LINEERR_INVALBEARERMODE") },                
	{ LINEERR_INVALCALLCOMPLMODE,		_T("LINEERR_INVALCALLCOMPLMODE") },             
	{ LINEERR_INVALCALLHANDLE,			_T("LINEERR_INVALCALLHANDLE") },                
	{ LINEERR_INVALCALLPARAMS,			_T("LINEERR_INVALCALLPARAMS") },                
	{ LINEERR_INVALCALLPRIVILEGE,		_T("LINEERR_INVALCALLPRIVILEGE") },             
	{ LINEERR_INVALCALLSELECT,			_T("LINEERR_INVALCALLSELECT") },                
	{ LINEERR_INVALCALLSTATE,			_T("LINEERR_INVALCALLSTATE") },                 
	{ LINEERR_INVALCALLSTATELIST,		_T("LINEERR_INVALCALLSTATELIST") },             
	{ LINEERR_INVALCARD,				_T("LINEERR_INVALCARD") },                      
	{ LINEERR_INVALCOMPLETIONID,		_T("LINEERR_INVALCOMPLETIONID") },              
	{ LINEERR_INVALCONFCALLHANDLE,		_T("LINEERR_INVALCONFCALLHANDLE") },            
	{ LINEERR_INVALCONSULTCALLHANDLE,	_T("LINEERR_INVALCONSULTCALLHANDLE") },         
	{ LINEERR_INVALCOUNTRYCODE,			_T("LINEERR_INVALCOUNTRYCODE") },               
	{ LINEERR_INVALDEVICECLASS,			_T("LINEERR_INVALDEVICECLASS") },               
	{ LINEERR_INVALDEVICEHANDLE,		_T("LINEERR_INVALDEVICEHANDLE") },              
	{ LINEERR_INVALDIALPARAMS,			_T("LINEERR_INVALDIALPARAMS") },                
	{ LINEERR_INVALDIGITLIST,			_T("LINEERR_INVALDIGITLIST") },                 
	{ LINEERR_INVALDIGITMODE,			_T("LINEERR_INVALDIGITMODE") },                 
	{ LINEERR_INVALDIGITS,				_T("LINEERR_INVALDIGITS") },                    
	{ LINEERR_INVALEXTVERSION,			_T("LINEERR_INVALEXTVERSION") },                
	{ LINEERR_INVALGROUPID,				_T("LINEERR_INVALGROUPID") },                   
	{ LINEERR_INVALLINEHANDLE,			_T("LINEERR_INVALLINEHANDLE") },                
	{ LINEERR_INVALLINESTATE,			_T("LINEERR_INVALLINESTATE") },                 
	{ LINEERR_INVALLOCATION,			_T("LINEERR_INVALLOCATION") },                  
	{ LINEERR_INVALMEDIALIST,			_T("LINEERR_INVALMEDIALIST") },                 
	{ LINEERR_INVALMEDIAMODE,			_T("LINEERR_INVALMEDIAMODE") },                 
	{ LINEERR_INVALMESSAGEID,			_T("LINEERR_INVALMESSAGEID") },                 
	{ LINEERR_INVALPARAM,				_T("LINEERR_INVALPARAM") },                     
	{ LINEERR_INVALPARKID,				_T("LINEERR_INVALPARKID") },                    
	{ LINEERR_INVALPARKMODE,			_T("LINEERR_INVALPARKMODE") },                  
	{ LINEERR_INVALPOINTER,				_T("LINEERR_INVALPOINTER") },                   
	{ LINEERR_INVALPRIVSELECT,			_T("LINEERR_INVALPRIVSELECT") },                
	{ LINEERR_INVALRATE,				_T("LINEERR_INVALRATE") },                      
	{ LINEERR_INVALREQUESTMODE,			_T("LINEERR_INVALREQUESTMODE") },               
	{ LINEERR_INVALTERMINALID,			_T("LINEERR_INVALTERMINALID") },                
	{ LINEERR_INVALTERMINALMODE,		_T("LINEERR_INVALTERMINALMODE") },              
	{ LINEERR_INVALTIMEOUT,				_T("LINEERR_INVALTIMEOUT") },                   
	{ LINEERR_INVALTONE,				_T("LINEERR_INVALTONE") },                      
	{ LINEERR_INVALTONELIST,			_T("LINEERR_INVALTONELIST") },                  
	{ LINEERR_INVALTONEMODE,			_T("LINEERR_INVALTONEMODE") },                  
	{ LINEERR_INVALTRANSFERMODE,		_T("LINEERR_INVALTRANSFERMODE") },              
	{ LINEERR_LINEMAPPERFAILED,			_T("LINEERR_LINEMAPPERFAILED") },               
	{ LINEERR_NOCONFERENCE,				_T("LINEERR_NOCONFERENCE") },                   
	{ LINEERR_NODEVICE,					_T("LINEERR_NODEVICE") },                       
	{ LINEERR_NODRIVER,					_T("LINEERR_NODRIVER") },                       
	{ LINEERR_NOMEM,					_T("LINEERR_NOMEM") },                          
	{ LINEERR_NOREQUEST,				_T("LINEERR_NOREQUEST") },                      
	{ LINEERR_NOTOWNER,					_T("LINEERR_NOTOWNER") },                       
	{ LINEERR_NOTREGISTERED,			_T("LINEERR_NOTREGISTERED") },                  
	{ LINEERR_OPERATIONFAILED,			_T("LINEERR_OPERATIONFAILED") },                
	{ LINEERR_OPERATIONUNAVAIL,			_T("LINEERR_OPERATIONUNAVAIL") },               
	{ LINEERR_RATEUNAVAIL,				_T("LINEERR_RATEUNAVAIL") },                    
	{ LINEERR_RESOURCEUNAVAIL,			_T("LINEERR_RESOURCEUNAVAIL") },                
	{ LINEERR_REQUESTOVERRUN,			_T("LINEERR_REQUESTOVERRUN") },                 
	{ LINEERR_STRUCTURETOOSMALL,		_T("LINEERR_STRUCTURETOOSMALL") },              
	{ LINEERR_TARGETNOTFOUND,			_T("LINEERR_TARGETNOTFOUND") },                 
	{ LINEERR_TARGETSELF,				_T("LINEERR_TARGETSELF") },                     
	{ LINEERR_UNINITIALIZED,			_T("LINEERR_UNINITIALIZED") },                  
	{ LINEERR_USERUSERINFOTOOBIG,		_T("LINEERR_USERUSERINFOTOOBIG") },             
	{ LINEERR_REINIT,					_T("LINEERR_REINIT") },                         
	{ LINEERR_ADDRESSBLOCKED,			_T("LINEERR_ADDRESSBLOCKED") },                 
	{ LINEERR_BILLINGREJECTED,			_T("LINEERR_BILLINGREJECTED") },                
	{ LINEERR_INVALFEATURE,				_T("LINEERR_INVALFEATURE") },                   
	{ LINEERR_NOMULTIPLEINSTANCE,		_T("LINEERR_NOMULTIPLEINSTANCE") },             
	{ LINEERR_INVALAGENTID,				_T("LINEERR_INVALAGENTID") },                   
	{ LINEERR_INVALAGENTGROUP,			_T("LINEERR_INVALAGENTGROUP") },                
	{ LINEERR_INVALPASSWORD,			_T("LINEERR_INVALPASSWORD") },                  
	{ LINEERR_INVALAGENTSTATE,			_T("LINEERR_INVALAGENTSTATE") },                
	{ LINEERR_INVALAGENTACTIVITY,		_T("LINEERR_INVALAGENTACTIVITY") },             
	{ LINEERR_DIALVOICEDETECT,			_T("LINEERR_DIALVOICEDETECT") },                
	{ LINEERR_USERCANCELLED,            _T("LINEERR_USERCANCELLED") },
	{ LINEERR_INVALADDRESSTYPE,         _T("LINEERR_INVALADDRESSTYPE") },
	{ LINEERR_INVALAGENTSESSIONSTATE,   _T("LINEERR_INVALAGENTSESSIONSTATE") },
	{ PHONEERR_ALLOCATED,				_T("PHONEERR_ALLOCATED") },                     
	{ PHONEERR_BADDEVICEID,				_T("PHONEERR_BADDEVICEID") },                   
	{ PHONEERR_INCOMPATIBLEAPIVERSION,	_T("PHONEERR_INCOMPATIBLEAPIVERSION") },        
	{ PHONEERR_INCOMPATIBLEEXTVERSION,	_T("PHONEERR_INCOMPATIBLEEXTVERSION") },        
	{ PHONEERR_INIFILECORRUPT,			_T("PHONEERR_INIFILECORRUPT") },                
	{ PHONEERR_INUSE,					_T("PHONEERR_INUSE") },                         
	{ PHONEERR_INVALAPPHANDLE,			_T("PHONEERR_INVALAPPHANDLE") },                
	{ PHONEERR_INVALAPPNAME,			_T("PHONEERR_INVALAPPNAME") },                  
	{ PHONEERR_INVALBUTTONLAMPID,		_T("PHONEERR_INVALBUTTONLAMPID") },             
	{ PHONEERR_INVALBUTTONMODE,			_T("PHONEERR_INVALBUTTONMODE") },               
	{ PHONEERR_INVALBUTTONSTATE,		_T("PHONEERR_INVALBUTTONSTATE") },              
	{ PHONEERR_INVALDATAID,				_T("PHONEERR_INVALDATAID") },                   
	{ PHONEERR_INVALDEVICECLASS,		_T("PHONEERR_INVALDEVICECLASS") },              
	{ PHONEERR_INVALEXTVERSION,			_T("PHONEERR_INVALEXTVERSION") },               
	{ PHONEERR_INVALHOOKSWITCHDEV,		_T("PHONEERR_INVALHOOKSWITCHDEV") },            
	{ PHONEERR_INVALHOOKSWITCHMODE,		_T("PHONEERR_INVALHOOKSWITCHMODE") },           
	{ PHONEERR_INVALLAMPMODE,			_T("PHONEERR_INVALLAMPMODE") },                 
	{ PHONEERR_INVALPARAM,				_T("PHONEERR_INVALPARAM") },                    
	{ PHONEERR_INVALPHONEHANDLE,		_T("PHONEERR_INVALPHONEHANDLE") },              
	{ PHONEERR_INVALPHONESTATE,			_T("PHONEERR_INVALPHONESTATE") },               
	{ PHONEERR_INVALPOINTER,			_T("PHONEERR_INVALPOINTER") },                  
	{ PHONEERR_INVALPRIVILEGE,			_T("PHONEERR_INVALPRIVILEGE") },                
	{ PHONEERR_INVALRINGMODE,			_T("PHONEERR_INVALRINGMODE") },                 
	{ PHONEERR_NODEVICE,				_T("PHONEERR_NODEVICE") },                      
	{ PHONEERR_NODRIVER,				_T("PHONEERR_NODRIVER") },                      
	{ PHONEERR_NOMEM,					_T("PHONEERR_NOMEM") },                         
	{ PHONEERR_NOTOWNER,				_T("PHONEERR_NOTOWNER") },                      
	{ PHONEERR_OPERATIONFAILED,			_T("PHONEERR_OPERATIONFAILED") },               
	{ PHONEERR_OPERATIONUNAVAIL,		_T("PHONEERR_OPERATIONUNAVAIL") },              
	{ PHONEERR_RESOURCEUNAVAIL,			_T("PHONEERR_RESOURCEUNAVAIL") },               
	{ PHONEERR_REQUESTOVERRUN,			_T("PHONEERR_REQUESTOVERRUN") },                
	{ PHONEERR_STRUCTURETOOSMALL,		_T("PHONEERR_STRUCTURETOOSMALL") },             
	{ PHONEERR_UNINITIALIZED,			_T("PHONEERR_UNINITIALIZED") },                 
	{ PHONEERR_REINIT,					_T("PHONEERR_REINIT") },                        
	{ 0, NULL }
};

static DWtoString _LineFeatures[] = {
	{ LINEFEATURE_DEVSPECIFIC,			_T("DEVSPECIFIC") },                
	{ LINEFEATURE_DEVSPECIFICFEAT,		_T("DEVSPECIFICFEAT") },            
	{ LINEFEATURE_FORWARD,				_T("FORWARD") },                    
	{ LINEFEATURE_MAKECALL,				_T("MAKECALL") },                   
	{ LINEFEATURE_SETMEDIACONTROL,		_T("SETMEDIACONTROL") },            
	{ LINEFEATURE_SETTERMINAL,			_T("SETTERMINAL") },                
	{ LINEFEATURE_SETDEVSTATUS,			_T("SETDEVSTATUS") },               
	{ LINEFEATURE_FORWARDFWD,			_T("FORWARDFWD") },                 
	{ LINEFEATURE_FORWARDDND,			_T("FORWARDDND") },                 
	{ 0, NULL }
};

static DWtoString _ForwardModes[] = {
	{ LINEFORWARDMODE_UNCOND,			_T("UNCOND") },                 
	{ LINEFORWARDMODE_UNCONDINTERNAL,	_T("UNCONDINTERNAL") },         
	{ LINEFORWARDMODE_UNCONDEXTERNAL,	_T("UNCONDEXTERNAL") },         
	{ LINEFORWARDMODE_UNCONDSPECIFIC,	_T("UNCONDSPECIFIC") },         
	{ LINEFORWARDMODE_BUSY,				_T("BUSY") },                   
	{ LINEFORWARDMODE_BUSYINTERNAL,		_T("BUSYINTERNAL") },           
	{ LINEFORWARDMODE_BUSYEXTERNAL,		_T("BUSYEXTERNAL") },           
	{ LINEFORWARDMODE_BUSYSPECIFIC,		_T("BUSYSPECIFIC") },           
	{ LINEFORWARDMODE_NOANSW,			_T("NOANSW") },                 
	{ LINEFORWARDMODE_NOANSWINTERNAL,	_T("NOANSWINTERNAL") },         
	{ LINEFORWARDMODE_NOANSWEXTERNAL,	_T("NOANSWEXTERNAL") },         
	{ LINEFORWARDMODE_NOANSWSPECIFIC,	_T("NOANSWSPECIFIC") },         
	{ LINEFORWARDMODE_BUSYNA,			_T("BUSYNA") },                 
	{ LINEFORWARDMODE_BUSYNAINTERNAL,	_T("BUSYNAINTERNAL") },         
	{ LINEFORWARDMODE_BUSYNAEXTERNAL,	_T("BUSYNAEXTERNAL") },         
	{ LINEFORWARDMODE_BUSYNASPECIFIC,	_T("BUSYNASPECIFIC") },         
	{ LINEFORWARDMODE_UNKNOWN,			_T("UNKNOWN") },                
	{ LINEFORWARDMODE_UNAVAIL,			_T("UNAVAIL") },
	{ 0, NULL }
};

static DWtoString _LineIDSelect[] = {
	{ LINECALLSELECT_LINE,			_T("LINE") },                    
	{ LINECALLSELECT_ADDRESS,		_T("ADDRESS") },                 
	{ LINECALLSELECT_CALL,			_T("CALL") },                    
	{ LINECALLSELECT_DEVICEID,		_T("DEVICEID") },                
	{ LINECALLSELECT_CALLID,        _T("CALLID") },
	{ 0, NULL }
};

static DWtoString _MediaControl[] = {
	{ LINEMEDIACONTROL_NONE,			_T("NONE") },                  
	{ LINEMEDIACONTROL_START,			_T("START") },                 
	{ LINEMEDIACONTROL_RESET,			_T("RESET") },                 
	{ LINEMEDIACONTROL_PAUSE,			_T("PAUSE") },                 
	{ LINEMEDIACONTROL_RESUME,			_T("RESUME") },                
	{ LINEMEDIACONTROL_RATEUP,			_T("RATEUP") },                
	{ LINEMEDIACONTROL_RATEDOWN,		_T("RATEDOWN") },              
	{ LINEMEDIACONTROL_RATENORMAL,		_T("RATENORMAL") },            
	{ LINEMEDIACONTROL_VOLUMEUP,		_T("VOLUMEUP") },              
	{ LINEMEDIACONTROL_VOLUMEDOWN,		_T("VOLUMEDOWN") },            
	{ LINEMEDIACONTROL_VOLUMENORMAL,	_T("VOLUMENORMAL") },          
	{ 0, NULL }
};

static DWtoString _MediaModes[] = {
	{ LINEMEDIAMODE_UNKNOWN,			_T("UNKNOWN") },                  
	{ LINEMEDIAMODE_INTERACTIVEVOICE,	_T("INTERACTIVEVOICE") },         
	{ LINEMEDIAMODE_AUTOMATEDVOICE,		_T("AUTOMATEDVOICE") },           
	{ LINEMEDIAMODE_DATAMODEM,			_T("DATAMODEM") },                
	{ LINEMEDIAMODE_G3FAX,				_T("G3FAX") },                    
	{ LINEMEDIAMODE_TDD,				_T("TDD") },                      
	{ LINEMEDIAMODE_G4FAX,				_T("G4FAX") },                    
	{ LINEMEDIAMODE_DIGITALDATA,		_T("DIGITALDATA") },              
	{ LINEMEDIAMODE_TELETEX,			_T("TELETEX") },                  
	{ LINEMEDIAMODE_VIDEOTEX,			_T("VIDEOTEX") },                 
	{ LINEMEDIAMODE_TELEX,				_T("TELEX") },                    
	{ LINEMEDIAMODE_MIXED,				_T("MIXED") },                    
	{ LINEMEDIAMODE_ADSI,				_T("ADSI") },                     
	{ LINEMEDIAMODE_VOICEVIEW,			_T("VOICEVIEW") },                
	{ LINEMEDIAMODE_VIDEO,				_T("VIDEO") },                    
	{ 0, NULL }
};

static DWtoString _OfferingModes[] = {
	{ LINEOFFERINGMODE_ACTIVE,		_T("ACTIVE") },                
	{ LINEOFFERINGMODE_INACTIVE,	_T("INACTIVE") },              
	{ 0, NULL }
};

static DWtoString _ParkModes[] = {
	{ LINEPARKMODE_DIRECTED,		_T("DIRECTED") },                  
	{ LINEPARKMODE_NONDIRECTED,		_T("NONDIRECTED") },               
	{ 0, NULL }
};

static DWtoString _RemoveFromConf[] = {
	{ LINEREMOVEFROMCONF_NONE,			_T("NONE") },                
	{ LINEREMOVEFROMCONF_LAST,			_T("LAST") },                
	{ LINEREMOVEFROMCONF_ANY,			_T("ANY") },                 
	{ 0, NULL }
};

static DWtoString _RoamModes[] = {
	{ LINEROAMMODE_UNKNOWN,			_T("UNKNOWN") },                   
	{ LINEROAMMODE_UNAVAIL,			_T("UNAVAIL") },                   
	{ LINEROAMMODE_HOME,			_T("HOME") },                      
	{ LINEROAMMODE_ROAMA,			_T("ROAMA") },                     
	{ LINEROAMMODE_ROAMB,			_T("ROAMB") },                     
	{ 0, NULL }
};

static DWtoString _SpecialInfo[] = {
	{ LINESPECIALINFO_NOCIRCUIT,	_T("NOCIRCUIT") },
	{ LINESPECIALINFO_CUSTIRREG,	_T("CUSTIRREG") },
	{ LINESPECIALINFO_REORDER,		_T("REORDER") },
	{ LINESPECIALINFO_UNKNOWN,		_T("UNKNOWN") },
	{ LINESPECIALINFO_UNAVAIL,		_T("UNAVAIL") },
	{ 0, NULL }
};

static DWtoString _StringFormats[] = {
    { STRINGFORMAT_ASCII,		_T("ASCII") },
    { STRINGFORMAT_BINARY,		_T("BINARY") },
    { STRINGFORMAT_DBCS,		_T("DBCS") },
    { STRINGFORMAT_UNICODE,		_T("UNICODE") },
	{ 0, NULL }
};

static DWtoString _TermDevices[] = {
	{ LINETERMDEV_PHONE,			_T("PHONE") },                      
	{ LINETERMDEV_HEADSET,			_T("HEADSET") },                    
	{ LINETERMDEV_SPEAKER,			_T("SPEAKER") },                    
	{ 0, NULL }
};

static DWtoString _TermModes[] = {
	{ LINETERMMODE_BUTTONS,			_T("BUTTONS") },                   
	{ LINETERMMODE_LAMPS,			_T("LAMPS") },                     
	{ LINETERMMODE_DISPLAY,			_T("DISPLAY") },                   
	{ LINETERMMODE_RINGER,			_T("RINGER") },                    
	{ LINETERMMODE_HOOKSWITCH,		_T("HOOKSWITCH") },                
	{ LINETERMMODE_MEDIATOLINE,		_T("MEDIATOLINE") },               
	{ LINETERMMODE_MEDIAFROMLINE,	_T("MEDIAFROMLINE") },             
	{ LINETERMMODE_MEDIABIDIRECT,	_T("MEDIABIDIRECT") },             
	{ 0, NULL }
};

static DWtoString _ToneModes[] = {
	{ LINETONEMODE_CUSTOM,			_T("CUSTOM") },                    
	{ LINETONEMODE_RINGBACK,		_T("RINGBACK") },                  
	{ LINETONEMODE_BUSY,			_T("BUSY") },                      
	{ LINETONEMODE_BEEP,			_T("BEEP") },                      
	{ LINETONEMODE_BILLING,			_T("BILLING") },                   
	{ 0, NULL }
};

static DWtoString _TransferModes[] = {
	{ LINETRANSFERMODE_TRANSFER,		_T("TRANSFER") },              
	{ LINETRANSFERMODE_CONFERENCE,		_T("CONFERENCE") },            
	{ 0, NULL }
};

static DWtoString _ButtonFunctions[] = {
	{ PHONEBUTTONFUNCTION_UNKNOWN,			_T("UNKNOWN") },            
	{ PHONEBUTTONFUNCTION_CONFERENCE,		_T("CONFERENCE") },         
	{ PHONEBUTTONFUNCTION_TRANSFER,			_T("TRANSFER") },           
	{ PHONEBUTTONFUNCTION_DROP,				_T("DROP") },               
	{ PHONEBUTTONFUNCTION_HOLD,				_T("HOLD") },               
	{ PHONEBUTTONFUNCTION_RECALL,			_T("RECALL") },             
	{ PHONEBUTTONFUNCTION_DISCONNECT,		_T("DISCONNECT") },         
	{ PHONEBUTTONFUNCTION_CONNECT,			_T("CONNECT") },            
	{ PHONEBUTTONFUNCTION_MSGWAITON,		_T("MSGWAITON") },          
	{ PHONEBUTTONFUNCTION_MSGWAITOFF,		_T("MSGWAITOFF") },         
	{ PHONEBUTTONFUNCTION_SELECTRING,		_T("SELECTRING") },         
	{ PHONEBUTTONFUNCTION_ABBREVDIAL,		_T("ABBREVDIAL") },         
	{ PHONEBUTTONFUNCTION_FORWARD,			_T("FORWARD") },            
	{ PHONEBUTTONFUNCTION_PICKUP,			_T("PICKUP") },             
	{ PHONEBUTTONFUNCTION_RINGAGAIN,		_T("RINGAGAIN") },          
	{ PHONEBUTTONFUNCTION_PARK,				_T("PARK") },               
	{ PHONEBUTTONFUNCTION_REJECT,			_T("REJECT") },             
	{ PHONEBUTTONFUNCTION_REDIRECT,			_T("REDIRECT") },           
	{ PHONEBUTTONFUNCTION_MUTE,				_T("MUTE") },               
	{ PHONEBUTTONFUNCTION_VOLUMEUP,			_T("VOLUMEUP") },           
	{ PHONEBUTTONFUNCTION_VOLUMEDOWN,		_T("VOLUMEDOWN") },         
	{ PHONEBUTTONFUNCTION_SPEAKERON,		_T("SPEAKERON") },          
	{ PHONEBUTTONFUNCTION_SPEAKEROFF,		_T("SPEAKEROFF") },         
	{ PHONEBUTTONFUNCTION_FLASH,			_T("FLASH") },              
	{ PHONEBUTTONFUNCTION_DATAON,			_T("DATAON") },             
	{ PHONEBUTTONFUNCTION_DATAOFF,			_T("DATAOFF") },            
	{ PHONEBUTTONFUNCTION_DONOTDISTURB,		_T("DONOTDISTURB") },       
	{ PHONEBUTTONFUNCTION_INTERCOM,			_T("INTERCOM") },           
	{ PHONEBUTTONFUNCTION_BRIDGEDAPP,		_T("BRIDGEDAPP") },         
	{ PHONEBUTTONFUNCTION_BUSY,				_T("BUSY") },               
	{ PHONEBUTTONFUNCTION_CALLAPP,			_T("CALLAPP") },            
	{ PHONEBUTTONFUNCTION_DATETIME,			_T("DATETIME") },           
	{ PHONEBUTTONFUNCTION_DIRECTORY,		_T("DIRECTORY") },          
	{ PHONEBUTTONFUNCTION_COVER,			_T("COVER") },              
	{ PHONEBUTTONFUNCTION_CALLID,			_T("CALLID") },             
	{ PHONEBUTTONFUNCTION_LASTNUM,			_T("LASTNUM") },            
	{ PHONEBUTTONFUNCTION_NIGHTSRV,			_T("NIGHTSRV") },           
	{ PHONEBUTTONFUNCTION_SENDCALLS,		_T("SENDCALLS") },          
	{ PHONEBUTTONFUNCTION_MSGINDICATOR,		_T("MSGINDICATOR") },       
	{ PHONEBUTTONFUNCTION_REPDIAL,			_T("REPDIAL") },            
	{ PHONEBUTTONFUNCTION_SETREPDIAL,		_T("SETREPDIAL") },         
	{ PHONEBUTTONFUNCTION_SYSTEMSPEED,		_T("SYSTEMSPEED") },        
	{ PHONEBUTTONFUNCTION_STATIONSPEED,		_T("STATIONSPEED") },       
	{ PHONEBUTTONFUNCTION_CAMPON,			_T("CAMPON") },             
	{ PHONEBUTTONFUNCTION_SAVEREPEAT,		_T("SAVEREPEAT") },         
	{ PHONEBUTTONFUNCTION_QUEUECALL,		_T("QUEUECALL") },          
	{ PHONEBUTTONFUNCTION_NONE,				_T("NONE") },               
	{ 0, NULL }
};

static DWtoString _ButtonModes[] = {
	{ PHONEBUTTONMODE_DUMMY,			_T("DUMMY") },                  
	{ PHONEBUTTONMODE_CALL,				_T("CALL") },                   
	{ PHONEBUTTONMODE_FEATURE,			_T("FEATURE") },                
	{ PHONEBUTTONMODE_KEYPAD,			_T("KEYPAD") },                 
	{ PHONEBUTTONMODE_LOCAL,			_T("LOCAL") },                  
	{ PHONEBUTTONMODE_DISPLAY,			_T("DISPLAY") },                
	{ 0, NULL }
};

static DWtoString _ButtonStates[] = {
	{ PHONEBUTTONSTATE_UP,			_T("UP") },                    
	{ PHONEBUTTONSTATE_DOWN,		_T("DOWN") },                  
	{ PHONEBUTTONSTATE_UNKNOWN,		_T("UNKNOWN") },               
	{ PHONEBUTTONSTATE_UNAVAIL,		_T("UNAVAIL") },               
	{ 0, NULL }
};

static DWtoString _PhoneFeatures[] = {
	{ PHONEFEATURE_GETBUTTONINFO,		_T("GETBUTTONINFO") },             
	{ PHONEFEATURE_GETDATA,				_T("GETDATA") },                   
	{ PHONEFEATURE_GETDISPLAY,			_T("GETDISPLAY") },                
	{ PHONEFEATURE_GETGAINHANDSET,		_T("GETGAINHANDSET") },            
	{ PHONEFEATURE_GETGAINSPEAKER,		_T("GETGAINSPEAKER") },            
	{ PHONEFEATURE_GETGAINHEADSET,		_T("GETGAINHEADSET") },            
	{ PHONEFEATURE_GETHOOKSWITCHHANDSET,_T("GETHOOKSWITCHHANDSET") },      
	{ PHONEFEATURE_GETHOOKSWITCHSPEAKER,_T("GETHOOKSWITCHSPEAKER") },      
	{ PHONEFEATURE_GETHOOKSWITCHHEADSET,_T("GETHOOKSWITCHHEADSET") },      
	{ PHONEFEATURE_GETLAMP,				_T("GETLAMP") },                   
	{ PHONEFEATURE_GETRING,				_T("GETRING") },                   
	{ PHONEFEATURE_GETVOLUMEHANDSET,	_T("GETVOLUMEHANDSET") },          
	{ PHONEFEATURE_GETVOLUMESPEAKER,	_T("GETVOLUMESPEAKER") },          
	{ PHONEFEATURE_GETVOLUMEHEADSET,	_T("GETVOLUMEHEADSET") },          
	{ PHONEFEATURE_SETBUTTONINFO,		_T("SETBUTTONINFO") },             
	{ PHONEFEATURE_SETDATA,				_T("SETDATA") },                   
	{ PHONEFEATURE_SETDISPLAY,			_T("SETDISPLAY") },                
	{ PHONEFEATURE_SETGAINHANDSET,		_T("SETGAINHANDSET") },            
	{ PHONEFEATURE_SETGAINSPEAKER,		_T("SETGAINSPEAKER") },            
	{ PHONEFEATURE_SETGAINHEADSET,		_T("SETGAINHEADSET") },            
	{ PHONEFEATURE_SETHOOKSWITCHHANDSET,_T("SETHOOKSWITCHHANDSET") },      
	{ PHONEFEATURE_SETHOOKSWITCHSPEAKER,_T("SETHOOKSWITCHSPEAKER") },      
	{ PHONEFEATURE_SETHOOKSWITCHHEADSET,_T("SETHOOKSWITCHHEADSET") },      
	{ PHONEFEATURE_SETLAMP,				_T("SETLAMP") },                   
	{ PHONEFEATURE_SETRING,				_T("SETRING") },                   
	{ PHONEFEATURE_SETVOLUMEHANDSET,	_T("SETVOLUMEHANDSET") },          
	{ PHONEFEATURE_SETVOLUMESPEAKER,	_T("SETVOLUMESPEAKER") },          
	{ PHONEFEATURE_SETVOLUMEHEADSET,	_T("SETVOLUMEHEADSET") },          
	{ 0, NULL }
};

static DWtoString _HookswitchDevs[] = {
	{ PHONEHOOKSWITCHDEV_HANDSET,			_T("HANDSET") },             
	{ PHONEHOOKSWITCHDEV_SPEAKER,			_T("SPEAKER") },             
	{ PHONEHOOKSWITCHDEV_HEADSET,			_T("HEADSET") },             
	{ 0, NULL }
};

static DWtoString _HookswitchModes[] = {
	{ PHONEHOOKSWITCHMODE_ONHOOK,		_T("ONHOOK") },             
	{ PHONEHOOKSWITCHMODE_MIC,			_T("MIC") },                
	{ PHONEHOOKSWITCHMODE_SPEAKER,		_T("SPEAKER") },            
	{ PHONEHOOKSWITCHMODE_MICSPEAKER,	_T("MICSPEAKER") },         
	{ PHONEHOOKSWITCHMODE_UNKNOWN,		_T("UNKNOWN") },            
	{ 0, NULL }
};

static DWtoString _LampModes[] = {
	{ PHONELAMPMODE_DUMMY,			_T("DUMMY") },                    
	{ PHONELAMPMODE_OFF,			_T("OFF") },                      
	{ PHONELAMPMODE_STEADY,			_T("STEADY") },                   
	{ PHONELAMPMODE_WINK,			_T("WINK") },                     
	{ PHONELAMPMODE_FLASH,			_T("FLASH") },                    
	{ PHONELAMPMODE_FLUTTER,		_T("FLUTTER") },                  
	{ PHONELAMPMODE_BROKENFLUTTER,	_T("BROKENFLUTTER") },            
	{ PHONELAMPMODE_UNKNOWN,		_T("UNKNOWN") },                  
	{ 0, NULL }
};

static DWtoString _PhoneStates[] = {
	{ PHONESTATE_OTHER,				_T("OTHER") },                       
	{ PHONESTATE_CONNECTED,			_T("CONNECTED") },                   
	{ PHONESTATE_DISCONNECTED,		_T("DISCONNECTED") },                
	{ PHONESTATE_OWNER,				_T("OWNER") },                       
	{ PHONESTATE_MONITORS,			_T("MONITORS") },                    
	{ PHONESTATE_DISPLAY,			_T("DISPLAY") },                     
	{ PHONESTATE_LAMP,				_T("LAMP") },                        
	{ PHONESTATE_RINGMODE,			_T("RINGMODE") },                    
	{ PHONESTATE_RINGVOLUME,		_T("RINGVOLUME") },                  
	{ PHONESTATE_HANDSETHOOKSWITCH,	_T("HANDSETHOOKSWITCH") },           
	{ PHONESTATE_HANDSETVOLUME,		_T("HANDSETVOLUME") },               
	{ PHONESTATE_HANDSETGAIN,		_T("HANDSETGAIN") },                 
	{ PHONESTATE_SPEAKERHOOKSWITCH,	_T("SPEAKERHOOKSWITCH") },           
	{ PHONESTATE_SPEAKERVOLUME,		_T("SPEAKERVOLUME") },               
	{ PHONESTATE_SPEAKERGAIN,		_T("SPEAKERGAIN") },                 
	{ PHONESTATE_HEADSETHOOKSWITCH,	_T("HEADSETHOOKSWITCH") },           
	{ PHONESTATE_HEADSETVOLUME,		_T("HEADSETVOLUME") },               
	{ PHONESTATE_HEADSETGAIN,		_T("HEADSETGAIN") },                 
	{ PHONESTATE_SUSPEND,			_T("SUSPEND") },                     
	{ PHONESTATE_RESUME,			_T("RESUME") },                      
	{ PHONESTATE_DEVSPECIFIC,		_T("DEVSPECIFIC") },                 
	{ PHONESTATE_REINIT,			_T("REINIT") },                      
	{ PHONESTATE_CAPSCHANGE,		_T("CAPSCHANGE") },                  
	{ PHONESTATE_REMOVED,			_T("REMOVED") },                     
	{ 0, NULL }
};

static DWtoString _PhoneStatusFlags[] = {
	{ PHONESTATUSFLAGS_CONNECTED,	_T("CONNECTED") },             
	{ PHONESTATUSFLAGS_SUSPENDED,	_T("SUSPENDED") },             
	{ 0, NULL }
};

static DWtoString _ObjectTypes[] = {
	{ TUISPIDLL_OBJECT_LINEID,			_T("OBJECT_LINEID") },                
	{ TUISPIDLL_OBJECT_PHONEID,			_T("OBJECT_PHONEID") },               
	{ TUISPIDLL_OBJECT_PROVIDERID,		_T("OBJECT_PROVIDERID") },            
	{ TUISPIDLL_OBJECT_DIALOGINSTANCE,	_T("OBJECT_DIALOGINSTANCE") },        
	{ 0, NULL }
};

static DWtoString _TSPIOptions[] = {
	{ LINETSPIOPTION_NONREENTRANT,		_T("NONREENTRANT") },            
	{ 0, NULL }
};
