//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TSPWizard.rc
//
#define IDI_TSPWIZARD                   1
#define IDS_CANNOTBEBLANK               1
#define IDS_NOUUISELECTED               2
#define IDS_MUSTENTERGROUPS             3
#define IDS_YOUMUSTSELECT               4
#define IDS_NODUPSALLOWED               5
#define IDS_NOTERMINALS                 6
#define IDS_NOLINEPHONE                 7
#define IDS_YOUMUSTENTER                8
#define IDS_NOIO                        9
#define IDS_NEEDDEFAULTDP               10
#define IDS_MINMAXERR                   11
#define IDS_NOBUFFERS                   12
#define IDS_DOWNLOADPROPS               13
#define IDS_ADD                         14
#define IDS_EDIT                        15
#define IDS_MUSTADDDEVS                 16
#define IDS_MAXPROB                     17
#define IDS_CANNOTBEZERO                18
#define IDS_HASUI                       19
#define IDS_MUSTUSENT5                  20
#define IDS_FAILED_CREATE_DIR           21
#define IDS_FAILED_CREATEFILE           22
#define IDS_BAD_CONFIG                  23
#define IDS_BADDIRECTORYPATH            24
#define IDS_CAPTION                     25
#define IDS_PROJECTEXISTS               26
#define IDD_CONFERENCE                  121
#define IDD_AGENTPROP                   122
#define IDD_UUIPROP                     123
#define IDD_CALLCOMPL                   124
#define IDD_CALLERID                    125
#define IDD_ACCEPT                      127
#define IDD_ANSWER                      128
#define IDD_TRANSFER                    134
#define IDD_HOLD                        135
#define IDD_FORWARD                     136
#define IDD_PARK                        137
#define IDD_PICKUP                      138
#define IDD_SECURE                      139
#define IDD_CALLTREATMENT               140
#define IDD_PREDDIALER                  141
#define IDD_GENERATEDIGITS              142
#define IDD_GENERATET                   143
#define IDD_MONITORTONE                 144
#define IDD_MONITORD                    145
#define IDD_BLINDXFER                   146
#define IDB_LOGO1                       147
#define IDD_MEDIACONTROL                148
#define IDD_TERMINALS                   149
#define IDD_DIALPARAMS                  151
#define IDD_DIALTONES                   152
#define IDD_DIALCHARS                   187
#define IDD_UPDOWNBUFF                  190
#define IDD_DISPLAY                     191
#define IDD_BUTTONS                     193
#define IDD_HSWITCH                     201
#define IDD_RINGERS                     202
#define IDR_241                         224
#define IDD_CUSTOM0                     1000
#define IDC_PICTURE                     1000
#define IDD_CUSTOM1                     1001
#define IDD_CUSTOM2                     1002
#define IDD_CUSTOM2_3                   1003
#define IDD_CUSTOM3                     1004
#define IDC_HASPHONEINT                 1004
#define IDD_CUSTOM4                     1005
#define IDC_HASCOMMENTS                 1005
#define IDC_USESWINSOCK                 1005
#define IDD_CUSTOM5                     1006
#define IDC_NOCOMMENTS                  1006
#define IDC_USECOMM                     1006
#define IDC_HASUI                       1007
#define IDC_USEOTHER                    1007
#define IDC_CREATEPOOLMGR               1008
#define IDC_SPEAKER                     1008
#define IDC_PROVINFO                    1009
#define IDC_SWITCHINFO                  1010
#define IDC_LINEFUNCS                   1010
#define IDC_ADDRCOUNT                   1011
#define IDC_LINEFUNCS2                  1011
#define IDC_SPIN1                       1012
#define IDC_MAXONHOLD                   1013
#define IDC_HANDSET                     1013
#define IDC_MAXTRANSFINCONF             1013
#define IDC_SPIN3                       1013
#define IDC_ADDRCOUNT2                  1013
#define IDC_SPIN2                       1014
#define IDC_HEADSET                     1014
#define IDC_SPIN4                       1014
#define IDC_CLASSES                     1015
#define IDC_SPIN5                       1015
#define IDC_EDIT1                       1016
#define IDC_SPIN6                       1016
#define IDC_CLASSNAME                   1016
#define IDC_MESSAGE                     1016
#define IDC_NAME                        1016
#define IDC_HEADER                      1017
#define IDC_SPIN7                       1017
#define IDC_BASECLASS                   1018
#define IDC_COMPANYNAME                 1018
#define IDC_SPIN8                       1018
#define IDC_CPPFILE                     1019
#define IDC_SPIN9                       1019
#define IDC_WANTTRACER                  1020
#define IDC_SPIN10                      1020
#define IDC_SPIN11                      1021
#define IDC_WINNT                       1021
#define IDC_EVENTOBJNAME                1022
#define IDC_SPIN12                      1022
#define IDC_SPIN13                      1023
#define IDC_PHONEFUNCS                  1025
#define IDC_REMOVEWHEN                  1028
#define IDC_REMOVESTATE                 1029
#define IDC_MAXCALLSINCONFERENCE        1030
#define IDC_ADDHELD                     1031
#define IDC_GROUPS                      1031
#define IDC_ANSWER                      1031
#define IDC_MAXFWDCALLID                1031
#define IDC_DIGIT_MIN                   1031
#define IDC_WIDTH                       1031
#define IDC_DEFGAIN                     1031
#define IDC_DROP                        1032
#define IDC_STATES                      1032
#define IDC_PLACE                       1032
#define IDC_MINRINGS                    1032
#define IDC_MAXCS                       1032
#define IDC_DUR_MIN                     1032
#define IDC_CREATENOHOLD                1033
#define IDC_ACTIVITIES                  1033
#define IDC_DROPCALL                    1033
#define IDC_MAXRINGS                    1033
#define IDC_MAXMEDIAMODES               1033
#define IDC_TONE_MIN                    1033
#define IDC_LISTSTATES                  1034
#define IDC_SEND                        1034
#define IDC_CREATEWOCALL                1034
#define IDC_PAUSE_MAX                   1034
#define IDC_CHECK1                      1035
#define IDC_CROSSADDR                   1035
#define IDC_REQUIRESID                  1035
#define IDC_DIGIT_MAX                   1035
#define IDC_CHECK2                      1036
#define IDC_DUR_MAX                     1036
#define IDC_CHECK3                      1037
#define IDC_TONE_MAX                    1037
#define IDC_CHECK4                      1038
#define IDC_PAUSE_DEF                   1038
#define IDC_CHECK5                      1039
#define IDC_DIGIT_DEF                   1039
#define IDC_ACCEPT                      1040
#define IDC_DUR_DEF                     1040
#define IDC_AGENTGROUPS                 1041
#define IDC_TONE_DEF                    1041
#define IDC_MEDIALIST                   1042
#define IDC_TYPES                       1043
#define IDC_COMPLMODE                   1044
#define IDC_COMPLTXT                    1045
#define IDC_ADD                         1046
#define IDC_REMOVE                      1047
#define IDC_MAXCALLCOMPL                1048
#define IDC_CALLERID                    1049
#define IDC_BLOCKED                     1050
#define IDC_SPECIFYRINGS                1050
#define IDC_BLOCKED2                    1051
#define IDC_ACCEPTTOALERT               1051
#define IDC_BLOCKED3                    1052
#define IDC_DROPPED                     1052
#define IDC_ONHOLD                      1053
#define IDC_NONE                        1054
#define IDC_HOLDTRANSF                  1055
#define IDC_MAKETRANSF                  1056
#define IDC_CONSULTATION                1056
#define IDC_STATUSVALID                 1057
#define IDC_INTEXT                      1058
#define IDC_BUSYNA                      1059
#define IDC_MODELIST                    1060
#define IDC_MAXFWDENTRIES               1061
#define IDC_DIRECTED                    1062
#define IDC_NONDIRECTED                 1063
#define IDC_GROUPID                     1064
#define IDC_CALLWAITING                 1065
#define IDC_SECURE                      1066
#define IDC_LIST                        1067
#define IDC_MAXCALLS                    1069
#define IDC_MAXTIMEOUT                  1070
#define IDC_TIMEOUT                     1071
#define IDC_PULSE                       1072
#define IDC_TONE                        1073
#define IDC_TONELIST                    1073
#define IDC_MAXTONES                    1074
#define IDC_MAXFREQ                     1075
#define IDC_HOLDMAKESNEW                1077
#define IDC_SWAPHOLD                    1078
#define IDC_NOINTERNAL                  1078
#define IDC_NOEXTERNAL                  1079
#define IDC_TAPIVER                     1079
#define IDC_USEPOOLMGR                  1080
#define IDC_MAXDIGITS                   1081
#define IDC_DEVTYPE                     1082
#define IDC_SHARING                     1083
#define IDC_TERMMODES                   1084
#define IDC_TERMINALS                   1085
#define IDC_DEFTERMMODES                1086
#define IDC_MEDIADIRECTION              1088
#define IDC_ADDRESS                     1091
#define IDC_CALL                        1092
#define IDC_LBLIST                      1093
#define IDC_CONFCALL                    1094
#define IDC_PAUSE_MIN                   1094
#define IDC_DIALTONES                   1095
#define IDC_BILLING                     1096
#define IDC_DIALTONE                    1097
#define IDC_BUFFERS                     1097
#define IDC_BUFFERSIZE                  1099
#define IDC_HEIGHT                      1100
#define IDC_CANREADDISPLAY              1102
#define IDC_CANUPDATEDISPLAY            1103
#define IDC_BUTTONWRITE                 1105
#define IDC_LAMPWRITE                   1106
#define IDC_FUNCTION                    1108
#define IDC_MODES                       1110
#define IDC_MODE                        1111
#define IDC_DEVICE                      1111
#define IDC_AVAIL                       1112
#define IDC_SETTABLE                    1113
#define IDC_VOLCHANGE                   1114
#define IDC_GAINCHANGE                  1115
#define IDC_DEFVOL                      1116
#define IDC_MAXRINGSTYLES               1117
#define IDC_WRITE                       1118
#define IDC_DEFRINGSTYLE                1119
#define IDC_PROJECTNAME                 1119
#define IDC_PATH                        1120
#define IDC_BROWSE                      1121
#define IDC_COMPILERVER                 1122

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        225
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1123
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
