/***************************************************************************
//
// UNSOLICITED.CPP
//
// TAPI Service provider for TSP++ version 3.00
// Unsolicited event handler
//
// Copyright (C) 1999 JulMar Technology, Inc.
// All rights reserved
//
// Generated by the TSPWizard (C) JulMar Technology, Inc.
// 
/***************************************************************************/

/*----------------------------------------------------------------------------
	INCLUDE FILES
-----------------------------------------------------------------------------*/
#include "stdafx.h"
#include "TestTsp.h"

/*----------------------------------------------------------------------------
	DEBUG SUPPORT
-----------------------------------------------------------------------------*/
#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

/*****************************************************************************
** Procedure:  CTestTspLine::UnsolicitedEvent
**
** Arguments:  'lpBuff' - The event block pointer
**
** Returns:    void
**
** Description:  This function is called when no request processed a given
**               response from the device and it was directed at this line.
**
*****************************************************************************/
bool CTestTspLine::UnsolicitedEvent(LPCVOID lpBuff)
{

	// TODO: process the event block which was received.

	// This might include agent state changes, call creation, call destruction, 
	// call state changes, transfers, conferences, etc.

	// Use the relevent objects to change information - for example,
	// use the CTSPICallAppearance and change the call state using the "SetCallState"
	// method.

	// For an example of this, see the JTSP sample supplied with TSP++ 3.0

	return true;

}// CTestTspLine::UnsolicitedEvent
